import { CheckCircle, AlertCircle } from "lucide-react";

type VerificationBadgeProps = {
  vetVerified: boolean;
  verifiedAt?: string;
  verifiedBy?: {
    fullName: string;
    email: string;
  } | null;
};

export function VerificationBadge({ vetVerified, verifiedAt, verifiedBy }: VerificationBadgeProps) {
  if (vetVerified) {
    return (
      <div className="rounded-lg border border-green-200 bg-green-50 p-3">
        <div className="flex items-start gap-2">
          <CheckCircle className="mt-1 flex-shrink-0 text-green-600" size={20} />
          <div className="flex-1">
            <p className="font-semibold text-green-900">Veterinarian Verified</p>
            {verifiedBy && (
              <p className="text-sm text-green-700">
                Verified by {verifiedBy.fullName} on {verifiedAt && new Date(verifiedAt).toLocaleDateString()}
              </p>
            )}
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="rounded-lg border border-amber-200 bg-amber-50 p-3">
      <div className="flex items-start gap-2">
        <AlertCircle className="mt-1 flex-shrink-0 text-amber-600" size={20} />
        <div className="flex-1">
          <p className="font-semibold text-amber-900">AI-Generated Guide</p>
          <p className="text-sm text-amber-700">This care guide was generated by AI and should be reviewed by a licensed veterinarian before use.</p>
        </div>
      </div>
    </div>
  );
}
